### ISSUE TITLE
Masking part of IP's

### ISSUE THREAD

**Issue by sebw** [binf/u2_anon#1]
It would be nice if you could anonymize the last byte of an IP..

Like "client_netmask" in Squid.

http://www.squid-cache.org/Doc/config/client_netmask/

**Comment by binf** [comment]
I will look into this and update the issue with a prototype when i get time
to drop some code in.

**Comment by binf** [comment]
Can you test the anon-mask branch?

ex.

/home/binf/u2_anon/u2_anon/src/u2_anon  -4  0.255.0.255  -r
./merged.log.1368160114  -lep  -O  ./output

**Comment by binf** [comment]
Can you try the anon-mask branch?

Let me know if thats what you expected etc...

Ex:
/home/binf/u2_anon/u2_anon/src/u2_anon  -4  0.255.0.255  -r
./merged.log.1368160114  -lep  -O  ./output

original unified2 example:
(Event)
        sensor id: 0    event id: 210   event second: 1368161123
event microsecond: 383602
        sig id: 15      gen id: 129     revision: 1      classification: 3
        priority: 2     ip source: 125.230.58.95        ip destination:
192.168.215.100
        src port: 58361 dest port: 36669        protocol: 6
impact_flag: 0  blocked: 0
Packet
        sensor id: 0    event id: 210   event second: 1368161123
        packet second: 1368161123       packet microsecond: 383602
        linktype: 1     packet_length: 60
[    0] 00 22 15 3E E5 05 00 23 69 A5 D1 A4 08 00 45 00  .".>...#i.....E.
[   16] 00 28 EF 82 40 00 29 06 11 FB 7D E6 3A 5F C0 A8  .(..@.)...}.:_..
[   32] D7 64 E3 F9 8F 3D 98 B5 A7 F5 00 00 00 00 50 04  .d...=........P.
[   48] 00 00 AB AB 00 00 00 00 CE 1D EA 61              ...........a

masked stuff
(Event)
        sensor id: 0    event id: 210   event second: 1368161123
event microsecond: 383602
        sig id: 15      gen id: 129     revision: 1      classification: 3
        priority: 2     ip source: 0.230.0.95   ip destination: 0.168.0.100
        src port: 58361 dest port: 36669        protocol: 6
impact_flag: 0  blocked: 0
Packet
        sensor id: 0    event id: 210   event second: 1368161123
        packet second: 1368161123       packet microsecond: 383602
        linktype: 1     packet_length: 60
[    0] AA AA AA AA AA AA BB BB BB BB BB BB 08 00 45 00  ..............E.
[   16] 00 28 EF 82 40 00 29 06 5F FD 00 E6 00 5F 00 A8  .(..@.)._...._..
[   32] 00 64 E3 F9 8F 3D 98 B5 A7 F5 00 00 00 00 50 04  .d...=........P.
[   48] 00 00 F9 A7 00 00 00 00 00 00 00 00              ............

**Comment by sebw** [comment]
Looks good ! Thanks

**Comment by binf** [comment]
Ok i will add the same thing for ipv6 support and upstream the changes.
